#!/bin/bash

echo "=== Google OAuth2 Setup Instructions ==="
echo ""
echo "To use this time tracker, you need to configure Google Cloud:"
echo ""
echo "STEP 1: Enable Google Sheets API"
echo "========================================="
echo "Go to: https://console.developers.google.com/apis/api/sheets.googleapis.com/overview?project=517658468057"
echo "Click 'Enable API' and wait a few minutes"
echo ""
echo "STEP 2: Configure OAuth2 Client"
echo "========================================="
echo "1. Go to: https://console.cloud.google.com/apis/credentials"
echo ""
echo "2. Find your OAuth 2.0 Client ID (the one used in .local/credentials.json)"
echo ""
echo "3. Click on it to edit"
echo ""
echo "4. Under 'Authorized redirect URIs', add:"
echo "   http://localhost:8080/callback"
echo ""
echo "5. Click 'Save'"
echo ""
echo "6. Now you can run: make auth"
echo ""
echo "Press Enter when you've completed these steps..."
read

echo "Testing authentication..."
./bin/timetracker -summary